In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

Using TensorFlow backend.


In [2]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]

In [4]:
#create label set for our data.
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [5]:
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)

In [6]:
#we need unique words for embedding
unique_words = set(all_words)
print(len(unique_words))

45


In [8]:
#we are converting the words to numbers using one-hot coding
vocab_length = len(corpus)
embedded_sentences = [one_hot(sent, vocab_length) for sent in corpus]
print(embedded_sentences )

[[1, 9, 8, 14, 14], [1, 2, 2, 3, 6, 12, 1], [5, 11, 10, 1, 9, 9], [1, 9], [5, 15, 1, 15, 6, 12, 1], [7, 2, 3, 13], [10, 9, 11, 2, 6, 14], [1, 9, 2, 5, 14], [7, 7], [14, 3, 13], [7, 5], [1, 2, 14, 3], [6, 2, 14, 12, 1, 14], [1, 14, 2, 7], [6, 12, 14, 9], [1, 7, 9, 7]]


In [9]:
#lamda fun which is anonymous function to find the length of all the sentences
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [10]:
#pad the sentences with equal length
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[ 1  9  8 14 14  0  0]
 [ 1  2  2  3  6 12  1]
 [ 5 11 10  1  9  9  0]
 [ 1  9  0  0  0  0  0]
 [ 5 15  1 15  6 12  1]
 [ 7  2  3 13  0  0  0]
 [10  9 11  2  6 14  0]
 [ 1  9  2  5 14  0  0]
 [ 7  7  0  0  0  0  0]
 [14  3 13  0  0  0  0]
 [ 7  5  0  0  0  0  0]
 [ 1  2 14  3  0  0  0]
 [ 6  2 14 12  1 14  0]
 [ 1 14  2  7  0  0  0]
 [ 6 12 14  9  0  0  0]
 [ 1  7  9  7  0  0  0]]


In [11]:
#Everything is ready for sentiment analysis using embedding
model = Sequential()
model.add(Embedding(vocab_length, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 20)             320       
_________________________________________________________________
flatten_1 (Flatten)          (None, 140)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 141       
Total params: 461
Trainable params: 461
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)


Epoch 1/100
16/16 [==============================] - 0s 20ms/step - loss: 0.6831 - acc: 0.5625
Epoch 2/100
16/16 [==============================] - 0s 120us/step - loss: 0.6800 - acc: 0.6875
Epoch 3/100
16/16 [==============================] - 0s 125us/step - loss: 0.6770 - acc: 0.6875
Epoch 4/100
16/16 [==============================] - 0s 187us/step - loss: 0.6740 - acc: 0.6875
Epoch 5/100
16/16 [==============================] - 0s 125us/step - loss: 0.6712 - acc: 0.7500
Epoch 6/100
16/16 [==============================] - 0s 187us/step - loss: 0.6682 - acc: 0.8125
Epoch 7/100
16/16 [==============================] - 0s 124us/step - loss: 0.6651 - acc: 0.8125
Epoch 8/100
16/16 [==============================] - 0s 164us/step - loss: 0.6622 - acc: 0.8750
Epoch 9/100
16/16 [==============================] - 0s 125us/step - loss: 0.6592 - acc: 0.8750
Epoch 10/100
16/16 [==============================] - 0s 154us/step - loss: 0.6562 - acc: 0.8750
Epoch 11/100
16/16 [===================

Epoch 84/100
16/16 [==============================] - 0s 183us/step - loss: 0.3867 - acc: 0.8750
Epoch 85/100
16/16 [==============================] - 0s 65us/step - loss: 0.3828 - acc: 0.8750
Epoch 86/100
16/16 [==============================] - 0s 125us/step - loss: 0.3789 - acc: 0.9375
Epoch 87/100
16/16 [==============================] - 0s 194us/step - loss: 0.3751 - acc: 0.9375
Epoch 88/100
16/16 [==============================] - 0s 118us/step - loss: 0.3712 - acc: 0.9375
Epoch 89/100
16/16 [==============================] - 0s 122us/step - loss: 0.3674 - acc: 0.9375
Epoch 90/100
16/16 [==============================] - 0s 250us/step - loss: 0.3636 - acc: 0.9375
Epoch 91/100
16/16 [==============================] - 0s 125us/step - loss: 0.3599 - acc: 0.9375
Epoch 92/100
16/16 [==============================] - 0s 125us/step - loss: 0.3561 - acc: 0.9375
Epoch 93/100
16/16 [==============================] - 0s 187us/step - loss: 0.3524 - acc: 0.9375
Epoch 94/100
16/16 [===========

In [14]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 93.750000
