In [2]:
import inltk

In [3]:
from inltk.inltk import tokenize

In [5]:
from inltk.inltk import setup
setup('ta')

RuntimeError: This event loop is already running

Done!


# Tokenize

In [8]:
from inltk.inltk import tokenize

In [11]:
text = """நீராருங் கடலுடுத்த நிலமடந்ைதக் ெகழிெலாழுகும்
சீராரும் வதனெமனத் திகழ்பரதக் கண்டமிதில்
ெதக்கணமும் அதிற்சிறந்த திராவிடநல் திருநாடும்
தக்கசிறு பிைறநுதலும் தரித்தநறுந் திலகமுேம!
அத்திலக வாசைனேபால் அைனத்துலகும் இன்பமுற
எத்திைசயும் புகழ்மணக்க இருந்தெபருந் தமிழணங்ேக!"""

# tokenize(input text, language code)
tokenize(text, "ta")


['▁நீரா',
 'ரு',
 'ங்',
 '▁கடல',
 'ு',
 'டு',
 'த்த',
 '▁நில',
 'மட',
 'ந்',
 'ை',
 'த',
 'க்',
 '▁',
 'ெ',
 'க',
 'ழி',
 'ெ',
 'லா',
 'ழு',
 'கு',
 'ம்',
 '▁சீ',
 'ரா',
 'ரும்',
 '▁வ',
 'த',
 'னெ',
 'மன',
 'த்',
 '▁திகழ',
 '்',
 'பர',
 'த',
 'க்',
 '▁கண்ட',
 'மி',
 'தில்',
 '▁',
 'ெ',
 'த',
 'க்கண',
 'மும்',
 '▁அதி',
 'ற்',
 'சிறந்த',
 '▁திராவிட',
 'ந',
 'ல்',
 '▁திரு',
 'நாடு',
 'ம்',
 '▁தக்க',
 'சிறு',
 '▁பி',
 'ை',
 'ற',
 'நு',
 'த',
 'லும்',
 '▁தர',
 'ித்த',
 'ந',
 'று',
 'ந்',
 '▁தி',
 'லக',
 'மு',
 'ே',
 'ம',
 '!',
 '▁அ',
 'த்தி',
 'லக',
 '▁வா',
 'சை',
 'னே',
 'பால்',
 '▁அ',
 'ை',
 'ன',
 'த்து',
 'லக',
 'ும்',
 '▁இன்',
 'ப',
 'மு',
 'ற',
 '▁எ',
 'த்தி',
 'ை',
 'ச',
 'யும்',
 '▁புகழ்',
 'மண',
 'க்க',
 '▁இருந்த',
 'ெ',
 'ப',
 'ரு',
 'ந்',
 '▁தமிழ',
 'ண',
 'ங்',
 'ே',
 'க',
 '!']

# Getting embedding vectors

In [4]:
from inltk.inltk import get_embedding_vectors

#vectors = get_embedding_vectors(text, 'ta') # where text is string in <code-of-language>


vectors = get_embedding_vectors('நீராருங் ', 'ta')
vectors[0].shape


(400,)

In [6]:
get_embedding_vectors('சீராரும் வதனெமனத் திகழ்பரதக் கண்டமிதில்','ta')

[array([-0.392376, -0.026561,  0.218991, -0.613945, ..., -0.468301,  0.088901,  0.606461,  0.141723], dtype=float32),
 array([ 0.241516, -0.136911,  0.356693, -0.873655, ..., -0.540106, -0.846683, -1.429399, -0.03362 ], dtype=float32),
 array([-0.121189, -0.060486,  0.203301,  0.097394, ..., -0.334376, -0.726214, -1.246265,  0.345443], dtype=float32),
 array([-0.268574,  0.578104, -0.092597, -0.100336, ..., -0.491912, -1.095734,  0.5956  ,  0.268935], dtype=float32),
 array([ 0.03303 , -0.013981, -0.955797, -0.016221, ..., -0.827908, -1.914278,  0.650999,  0.350428], dtype=float32),
 array([-0.035348,  0.201428,  0.392425, -0.107964, ..., -0.6994  , -0.521678, -0.437072, -0.293238], dtype=float32),
 array([-0.450861, -0.374799,  0.120025,  0.340392, ..., -0.403203,  0.117812,  0.70024 ,  0.504618], dtype=float32),
 array([ 0.090684, -0.043384,  0.830132,  0.777868, ..., -0.609601, -0.942782, -0.367691, -0.124289], dtype=float32),
 array([-0.54909 ,  0.03791 , -0.038977,  0.149942, ...,

In [7]:
len(vectors)

3

# Predict n words

In [10]:
from inltk.inltk import predict_next_words

text = """நீராருங் கடலுடுத்த நிலமடந்ைதக் ெகழிெலாழுகும்
சீராரும் வதனெமனத் திகழ்பரதக் கண்டமிதில்
ெதக்கணமும் அதிற்சிறந்த திராவிடநல் திருநாடும்
தக்கசிறு பிைறநுதலும் தரித்தநறுந் திலகமுேம!
அத்திலக வாசைனேபால் அைனத்துலகும் இன்பமுற
எத்திைசயும் புகழ்மணக்க இருந்தெபருந் தமிழணங்ேக!"""
predict_next_words(text , 2, 'ta') 

#text --> string in <code-of-language>
#n --> number of words you want to predict (integer)

'நீராருங் கடலுடுத்த நிலமடந்ைதக் ெகழிெலாழுகும்\nசீராரும் வதனெமனத் திகழ்பரதக் கண்டமிதில்\nெதக்கணமும் அதிற்சிறந்த திராவிடநல் திருநாடும்\nதக்கசிறு பிைறநுதலும் தரித்தநறுந் திலகமுேம!\nஅத்திலக வாசைனேபால் அைனத்துலகும் இன்பமுற\nஎத்திைசயும் புகழ்மணக்க இருந்தெபருந் தமிழணங்ேக! தண்டிற்கும்'

# Remove Foreign Languages

In [12]:
from inltk.inltk import remove_foreign_languages

text = """நீராருங் கடலுடுத்த நிலமடந்ைதக் ெகழிெலாழுகும்
சீராரும் வதனெமனத் திகழ்பரதக் கண்டமிதில்
ெதக்கணமும் அதிற்சிறந்த திராவிடநல் திருநாடும்
தக்கசிறு பிைறநுதலும் தரித்தநறுந் திலகமுேம!
அத்திலக வாசைனேபால் அைனத்துலகும் இன்பமுற
எத்திைசயும் புகழ்மணக்க இருந்தெபருந் தமிழணங்ேக!"""
remove_foreign_languages(text, 'ta')

#text --> string in one of the supported languages
#<code-of-language> --> code of that language whose words you want to retain

['▁நீரா',
 'ரு',
 'ங்',
 '▁கடல',
 'ு',
 'டு',
 'த்த',
 '▁நில',
 'மட',
 'ந்',
 'ை',
 'த',
 'க்',
 '▁',
 'ெ',
 'க',
 'ழி',
 'ெ',
 'லா',
 'ழு',
 'கு',
 'ம்',
 '▁சீ',
 'ரா',
 'ரும்',
 '▁வ',
 'த',
 'னெ',
 'மன',
 'த்',
 '▁திகழ',
 '்',
 'பர',
 'த',
 'க்',
 '▁கண்ட',
 'மி',
 'தில்',
 '▁',
 'ெ',
 'த',
 'க்கண',
 'மும்',
 '▁அதி',
 'ற்',
 'சிறந்த',
 '▁திராவிட',
 'ந',
 'ல்',
 '▁திரு',
 'நாடு',
 'ம்',
 '▁தக்க',
 'சிறு',
 '▁பி',
 'ை',
 'ற',
 'நு',
 'த',
 'லும்',
 '▁தர',
 'ித்த',
 'ந',
 'று',
 'ந்',
 '▁தி',
 'லக',
 'மு',
 'ே',
 'ம',
 '!',
 '▁அ',
 'த்தி',
 'லக',
 '▁வா',
 'சை',
 'னே',
 'பால்',
 '▁அ',
 'ை',
 'ன',
 'த்து',
 'லக',
 'ும்',
 '▁இன்',
 'ப',
 'மு',
 'ற',
 '▁எ',
 'த்தி',
 'ை',
 'ச',
 'யும்',
 '▁புகழ்',
 'மண',
 'க்க',
 '▁இருந்த',
 'ெ',
 'ப',
 'ரு',
 'ந்',
 '▁தமிழ',
 'ண',
 'ங்',
 'ே',
 'க',
 '!']

# Get Sentence Encoding

In [14]:
from inltk.inltk import get_sentence_encoding

get_sentence_encoding(text, 'ta')

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

array([-0.049043,  0.264813,  0.010338, -0.083325, ...,  0.027954, -0.013759, -0.238054, -0.015276], dtype=float32)

# get similar sentence

In [18]:
from inltk.inltk import get_similar_sentences

text = """நீராருங் கடலுடுத்த நிலமடந்ைதக் ெகழிெலாழுகும்
சீராரும் வதனெமனத் திகழ்பரதக் கண்டமிதில்
ெதக்கணமும் அதிற்சிறந்த திராவிடநல் திருநாடும்
தக்கசிறு பிைறநுதலும் தரித்தநறுந் திலகமுேம!
அத்திலக வாசைனேபால் அைனத்துலகும் இன்பமுற
எத்திைசயும் புகழ்மணக்க இருந்தெபருந் தமிழணங்ேக!"""

get_similar_sentences(text, 5 , 'ta', degree_of_aug = 0.1)

#where degree_of_aug is roughly the percentage of sentence you want to augment, with a default value of 0.1

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\hp\Anaconda3\lib\site-packages\torch\serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attr

['நீராருங் கடலுடுத்தம் நிலமடந்ைப்தக் ெகழிெலாழுகும் சீராரும் வதனெமனத் திகழ்கபரதக் கண்டமிதின் ெதக்கணமும் அதிற்பசிறந்த திராவிடநல் திருநாடும் தக்கசிறு பிைறேநுதலும் தரித்தநறுந் திலகமுேம! அத்தி C வாசைனேபால் அைனத்துலகும் இன்பமுற எத்திைசயும் புகழ்பெற்ற Proக்க இருந்தெபருந் தமிழணங்க்ேக!',
 'நீராருங்க் கடலுடும்த்த நிலமடந்ைதக் ெகEெலாழுகும் சீராரும் வதனெமனத் திகழ்கபரதக்கண்டமிதில் SOதக்கணமும் அதிற்சிறந்த திராவிடநல் Rநாடும் தக்கசிறு பிைறநுதலும் தரித்தநறுL திலகமுேம! அத்திலக வாசைனேAE அைனத்துலகும் இன்பமுற எத்திைசயும் புகழ்மணக்க இருந்தெபரூந் தமிழணங்ேக!',
 'நீராருங் கடலுடுத்த நிலமட Cைதக் ெகழிெலாழுகும்பா சீராரும் வதனெ Chத் திகழ்பரதல்க் கண்டமிதில் ெதக்கணமும் அதிற்குசிறந்த திராவிடநல் திருநாடும்பா தக்கசிறு பிைறாநுதலும் தரித்தநறுந் திலகமுேம! அத்திலக வாசைனேபால் அைனத்துPerும் இன்பத்துமுற எத்திைசயும் புகழ்மணக்க இருந்தெபருந் தமிழணங் Hக!',
 'நீராருங் கப்பலுடுத்த நிலமடந்ைதலக் ெக Hெலாழுகியம் சீராரிடம் வதனெமன Ch திகழ்பரதலக் கண்டமிதில் ெதக்கணமும் அதிற்சிறந்த திராவிடநல் திருநாடும் அதிகப்படியானசிறு பிைறநுதலும் தரித்தநறுந